In [6]:
import numpy as np

# Створення одновимірного масиву (вектора) з першими 10 натуральними числами
vector1 = np.arange(1, 11)
print("Вектор з першими 10 натуральними числами:")
print(vector1)

# Створення двовимірного масиву (матриці) розміром 3x3 з нулями
matrix1 = np.zeros((3, 3))
print("\nМатриця розміром 3x3 з нулями:")
print(matrix1)

# Створення масиву розміром 5x5 з випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, (5, 5))
print("\nМатриця розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(matrix2)

# Створення масиву розміром 4x4 з випадковими дійсними числами від 0 до 1
matrix3 = np.random.rand(4, 4)
print("\nМатриця розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(matrix3)

# Створення двох векторів розміром 5 з випадковими цілими числами від 1 до 10
vector2 = np.random.randint(1, 11, 5)
vector3 = np.random.randint(1, 11, 5)

# Виконання поелементних операцій
addition_result = vector2 + vector3
subtraction_result = vector2 - vector3
multiplication_result = vector2 * vector3

print("\nПоелементне додавання:")
print(addition_result)
print("\nПоелементне віднімання:")
print(subtraction_result)
print("\nПоелементне множення:")
print(multiplication_result)

# Створення двох векторів розміром 7 з довільними числами
vector4 = np.random.rand(7)
vector5 = np.random.rand(7)

# Знаходження скалярного добутку
scalar_product = np.dot(vector4, vector5)

print("\nСкалярний добуток двох векторів:")
print(scalar_product)

# Створення двох матриць розміром 2x2 та 2x3 з випадковими цілими числами від 1 до 10
matrix4 = np.random.randint(1, 11, (2, 2))
matrix5 = np.random.randint(1, 11, (2, 3))

# Перемноження матриць
matrix_product = np.dot(matrix4, matrix5)

print("\nПомноження двох матриць:")
print(matrix_product)

# Створення матриці розміром 3x3 з випадковими цілими числами від 1 до 10
matrix6 = np.random.randint(1, 11, (3, 3))

# Знаходження оберненої матриці
try:
    inverse_matrix = np.linalg.inv(matrix6)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nОбернена матриця не існує.")

# Створення матриці розміром 4x4 з випадковими дійсними числами від 0 до 1
matrix7 = np.random.rand(4, 4)

# Транспонування матриці
transposed_matrix = np.transpose(matrix7)

print("\nТранспонована матриця:")
print(transposed_matrix)

# Створення матриці розміром 3x4 та вектора розміром 4 з випадковими цілими числами
matrix8 = np.random.randint(1, 11, (3, 4))
vector6 = np.random.randint(1, 11, 4)

# Помноження матриці на вектор
matrix_vector_product = np.dot(matrix8, vector6)

print("\nМатриця, помножена на вектор:")
print(matrix_vector_product)

# Створення матриці розміром 2x3 та вектора розміром 3 з випадковими дійсними числами від 0 до 1
matrix9 = np.random.rand(2, 3)
vector7 = np.random.rand(3)

# Помноження матриці на вектор
matrix_vector_product2 = np.dot(matrix9, vector7)

print("\nМатриця, помножена на вектор:")
print(matrix_vector_product2)

# Створення двох матриць розміром 2x2 з випадковими цілими числами від 1 до 10
matrix10 = np.random.randint(1, 11, (2, 2))
matrix11 = np.random.randint(1, 11, (2, 2))

# Поелементне множення матриць
elementwise_product = matrix10 * matrix11

print("\nПоелементне множення двох матриць:")
print(elementwise_product)

# Створення двох матриць розміром 2x2 з випадковими цілими числами від 1 до 10
matrix12 = np.random.randint(1, 11, (2, 2))
matrix13 = np.random.randint(1, 11, (2, 2))

# Знаходження добутку матриць
matrix_product2 = np.dot(matrix12, matrix13)

print("\nДобуток двох матриць:")
print(matrix_product2)

# Створення матриці розміром 5x5 з випадковими цілими числами від 1 до 100
matrix14 = np.random.randint(1, 101, (5, 5))

# Знаходження суми елементів матриці
sum_of_elements = np.sum(matrix14)

print("\nСума елементів матриці:")
print(sum_of_elements)

# Створення двох матриць розміром 4x4 з випадковими цілими числами від 1 до 10
matrix15 = np.random.randint(1, 11, (4, 4))
matrix16 = np.random.randint(1, 11, (4, 4))

# Знаходження різниці матриць
difference_matrix = matrix15 - matrix16

print("\nРізниця двох матриць:")
print(difference_matrix)

# Створення матриці розміром 3x3 з випадковими дійсними числами від 0 до 1
matrix17 = np.random.rand(3, 3)

# Знаходження вектора-стовпчика зі сумами елементів кожного рядка матриці
row_sums = np.sum(matrix17, axis=1)

print("\nВектор-стовпчик із сумами елементів кожного рядка:")
print(row_sums)

# Створення матриці розміром 3x4 з довільними цілими числами
matrix18 = np.random.randint(1, 11, (3, 4))

# Створення матриці з квадратами чисел
squared_matrix = np.square(matrix18)

print("\nМатриця з квадратами чисел:")
print(squared_matrix)

# Створення вектора розміром 4 з випадковими цілими числами від 1 до 50
vector8 = np.random.randint(1, 51, 4)

# Знаходження вектора з квадратними коренями чисел
sqrt_vector = np.sqrt(vector8)

print("\nВектор з квадратними коренями чисел:")
print(sqrt_vector)


Вектор з першими 10 натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]

Матриця розміром 3x3 з нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Матриця розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 6  3  6  4  8]
 [ 7  2  8  4  4]
 [ 3  4  3 10  6]
 [ 3  5  4  5  3]
 [ 5  2  9  9  4]]

Матриця розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.64556064 0.99296438 0.7428697  0.52091158]
 [0.61671285 0.6110362  0.23344822 0.05784099]
 [0.73946026 0.51904311 0.11415196 0.3391112 ]
 [0.13060102 0.77604609 0.78893479 0.35567023]]

Поелементне додавання:
[17 13  5  3 13]

Поелементне віднімання:
[ 3 -3 -1  1  7]

Поелементне множення:
[70 40  6  2 30]

Скалярний добуток двох векторів:
1.1733002962189019

Помноження двох матриць:
[[54 55 77]
 [60 67 62]]

Обернена матриця:
[[ 6.25000000e-01 -7.50000000e-01  3.33066907e-17]
 [-1.37500000e+00  2.00000000e+00 -2.50000000e-01]
 [ 5.00000000e-01 -7.50000000e-01  2.50000000e-01]]

Транспонована матриця:
[[0.17760162 0.54760094 