In [1]:
import numpy as np

vector1 = np.arange(1, 11)
print("Вектор з першими 10 натуральними числами:")
print(vector1)

matrix1 = np.zeros((3, 3))
print("\nМатриця розміром 3x3 з нулями:")
print(matrix1)

matrix2 = np.random.randint(1, 11, (5, 5))
print("\nМатриця розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(matrix2)

matrix3 = np.random.rand(4, 4)
print("\nМатриця розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(matrix3)

vector2 = np.random.randint(1, 11, 5)
vector3 = np.random.randint(1, 11, 5)
addition_result = vector2 + vector3
subtraction_result = vector2 - vector3
multiplication_result = vector2 * vector3

print("\nПоелементне додавання:")
print(addition_result)
print("\nПоелементне віднімання:")
print(subtraction_result)
print("\nПоелементне множення:")
print(multiplication_result)

vector4 = np.random.rand(7)
vector5 = np.random.rand(7)
scalar_product = np.dot(vector4, vector5)

print("\nСкалярний добуток двох векторів:")
print(scalar_product)

matrix4 = np.random.randint(1, 11, (2, 2))
matrix5 = np.random.randint(1, 11, (2, 3))
matrix_product = np.dot(matrix4, matrix5)
print("\nПомноження двох матриць:")
print(matrix_product)

matrix6 = np.random.randint(1, 11, (3, 3))

try:
    inverse_matrix = np.linalg.inv(matrix6)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nОбернена матриця не існує.")

matrix7 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix7)
print("\nТранспонована матриця:")
print(transposed_matrix)

matrix8 = np.random.randint(1, 11, (3, 4))
vector6 = np.random.randint(1, 11, 4)
matrix_vector_product = np.dot(matrix8, vector6)
print("\nМатриця, помножена на вектор:")
print(matrix_vector_product)

matrix9 = np.random.rand(2, 3)
vector7 = np.random.rand(3)
matrix_vector_product2 = np.dot(matrix9, vector7)
print("\nМатриця, помножена на вектор:")
print(matrix_vector_product2)

matrix10 = np.random.randint(1, 11, (2, 2))
matrix11 = np.random.randint(1, 11, (2, 2))
elementwise_product = matrix10 * matrix11
print("\nПоелементне множення двох матриць:")
print(elementwise_product)

matrix12 = np.random.randint(1, 11, (2, 2))
matrix13 = np.random.randint(1, 11, (2, 2))
matrix_product2 = np.dot(matrix12, matrix13)
print("\nДобуток двох матриць:")
print(matrix_product2)

matrix14 = np.random.randint(1, 101, (5, 5))
sum_of_elements = np.sum(matrix14)
print("\nСума елементів матриці:")
print(sum_of_elements)

matrix15 = np.random.randint(1, 11, (4, 4))
matrix16 = np.random.randint(1, 11, (4, 4))
difference_matrix = matrix15 - matrix16
print("\nРізниця двох матриць:")
print(difference_matrix)

matrix17 = np.random.rand(3, 3)
row_sums = np.sum(matrix17, axis=1)
print("\nВектор-стовпчик із сумами елементів кожного рядка:")
print(row_sums)

matrix18 = np.random.randint(1, 11, (3, 4))
squared_matrix = np.square(matrix18)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

vector8 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector8)
print("\nВектор з квадратними коренями чисел:")
print(sqrt_vector)


Вектор з першими 10 натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]

Матриця розміром 3x3 з нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Матриця розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 5  6  5  2  2]
 [ 7  7  2  6  6]
 [10  6  7 10  9]
 [ 7 10  8 10  9]
 [ 3  7  4  4  4]]

Матриця розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.45140181 0.48108221 0.82431285 0.24762469]
 [0.79623361 0.83341319 0.94168015 0.80264057]
 [0.50547359 0.48409447 0.31261039 0.74635735]
 [0.60560412 0.48393417 0.90125521 0.0716752 ]]

Поелементне додавання:
[16 12 12 17 14]

Поелементне віднімання:
[ 2  0  6  3 -2]

Поелементне множення:
[63 36 27 70 48]

Скалярний добуток двох векторів:
1.4623603147107302

Помноження двох матриць:
[[63 21 18]
 [98 52 28]]

Обернена матриця:
[[ 0.19565217 -0.47826087  0.06521739]
 [-0.54347826  1.2173913   0.15217391]
 [ 0.41304348 -0.56521739 -0.19565217]]

Транспонована матриця:
[[0.84333816 0.18616167 0.12078928 0.17188178]
 [0.88504695 