In [1]:
import numpy as np

In [2]:
vector1 = np.arange(1, 11)
print("Вектор з першими 10 натуральними числами:")
print(vector1)

Вектор з першими 10 натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
matrix1 = np.zeros((3, 3))
print("\nМатриця розміром 3x3 з нулями:")
print(matrix1)


Матриця розміром 3x3 з нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
matrix2 = np.random.randint(1, 11, (5, 5))
print("\nМатриця розміром 5x5 з випадковими цілими числами від 1 до 10:")
print(matrix2)


Матриця розміром 5x5 з випадковими цілими числами від 1 до 10:
[[ 7  3  3  2  6]
 [ 5  5  6  5 10]
 [ 9  6  8 10  5]
 [ 9  6  6  6  9]
 [ 5  6  3  4 10]]


In [5]:
matrix3 = np.random.rand(4, 4)
print("\nМатриця розміром 4x4 з випадковими дійсними числами від 0 до 1:")
print(matrix3)


Матриця розміром 4x4 з випадковими дійсними числами від 0 до 1:
[[0.27209387 0.75330987 0.36165532 0.2620343 ]
 [0.34218326 0.16446342 0.27241772 0.43588376]
 [0.44494096 0.16541144 0.20600716 0.72221942]
 [0.20250799 0.93536318 0.09310115 0.69920046]]


In [6]:
vector2 = np.random.randint(1, 11, 5)
vector3 = np.random.randint(1, 11, 5)
addition_result = vector2 + vector3
subtraction_result = vector2 - vector3
multiplication_result = vector2 * vector3

print("\nПоелементне додавання:")
print(addition_result)
print("\nПоелементне віднімання:")
print(subtraction_result)
print("\nПоелементне множення:")
print(multiplication_result)


Поелементне додавання:
[ 9 11  2 14 11]

Поелементне віднімання:
[-3  1  0  4 -1]

Поелементне множення:
[18 30  1 45 30]


In [7]:
vector4 = np.random.rand(7)
vector5 = np.random.rand(7)
scalar_product = np.dot(vector4, vector5)

print("\nСкалярний добуток двох векторів:")
print(scalar_product)


Скалярний добуток двох векторів:
1.7840986074994094


In [8]:
matrix4 = np.random.randint(1, 11, (2, 2))
matrix5 = np.random.randint(1, 11, (2, 3))
matrix_product = np.dot(matrix4, matrix5)
print("\nПомноження двох матриць:")
print(matrix_product)


Помноження двох матриць:
[[74 82 80]
 [14 34 29]]


In [9]:
matrix6 = np.random.randint(1, 11, (3, 3))

try:
    inverse_matrix = np.linalg.inv(matrix6)
    print("\nОбернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nОбернена матриця не існує.")


Обернена матриця:
[[ 0.14516129 -0.22580645  0.16666667]
 [ 0.08064516  0.09677419 -0.16666667]
 [-0.11290323  0.06451613  0.16666667]]


In [29]:
matrix7 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix7)
print("\nТранспонована матриця:")
print(transposed_matrix)


Транспонована матриця:
[[0.79217636 0.76153523 0.94204148 0.51277707]
 [0.06779322 0.90460825 0.63307771 0.24440455]
 [0.09259912 0.89599115 0.14707145 0.79000465]
 [0.69709959 0.40817913 0.15844902 0.63971866]]


In [11]:
matrix8 = np.random.randint(1, 11, (3, 4))
vector6 = np.random.randint(1, 11, 4)
matrix_vector_product = np.dot(matrix8, vector6)
print("\nМатриця, помножена на вектор:")
print(matrix_vector_product)


Матриця, помножена на вектор:
[156 146 109]


In [12]:
matrix9 = np.random.rand(2, 3)
vector7 = np.random.rand(3)
matrix_vector_product2 = np.dot(matrix9, vector7)
print("\nМатриця, помножена на вектор:")
print(matrix_vector_product2)


Матриця, помножена на вектор:
[0.70360894 1.04594113]


In [13]:
matrix10 = np.random.randint(1, 11, (2, 2))
matrix11 = np.random.randint(1, 11, (2, 2))
elementwise_product = matrix10 * matrix11
print("\nПоелементне множення двох матриць:")
print(elementwise_product)


Поелементне множення двох матриць:
[[60 21]
 [21  9]]


In [14]:
matrix12 = np.random.randint(1, 11, (2, 2))
matrix13 = np.random.randint(1, 11, (2, 2))
matrix_product2 = np.dot(matrix12, matrix13)
print("\nДобуток двох матриць:")
print(matrix_product2)


Добуток двох матриць:
[[84 69]
 [66 59]]


In [27]:
matrix14 = np.random.randint(1, 101, (5, 5))
sum_of_elements = np.sum(matrix14)
print("\nСума елементів матриці:")
print(sum_of_elements)


Сума елементів матриці:
1146


In [26]:
matrix15 = np.random.randint(1, 11, (4, 4))
matrix16 = np.random.randint(1, 11, (4, 4))
difference_matrix = matrix15 - matrix16
print("\nРізниця двох матриць:")
print(difference_matrix)



Різниця двох матриць:
[[-5 -6 -2 -5]
 [ 3  8  8  2]
 [ 5 -3  1  8]
 [-1  4  1 -5]]


In [25]:
matrix17 = np.random.rand(3, 3)
row_sums = np.sum(matrix17, axis=1)
print("\nВектор-стовпчик із сумами елементів кожного рядка:")
print(row_sums)


Вектор-стовпчик із сумами елементів кожного рядка:
[1.23385236 1.33776957 0.81830727]


In [18]:
matrix18 = np.random.randint(1, 11, (3, 4))
squared_matrix = np.square(matrix18)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)


Матриця з квадратами чисел:
[[ 49  81   9   1]
 [ 25 100   1   4]
 [ 36  36  16   4]]


In [24]:
vector8 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector8)
print("\nВектор з квадратними коренями чисел:")
print(sqrt_vector)


Вектор з квадратними коренями чисел:
[5.38516481 3.46410162 7.07106781 5.65685425]
